= {product} - Hist贸rias de Usuario
Universidad Cat贸lica Boliviana. <bernardo.duran@ucb.edu.bo>
1.0.0
:product: BOT BUSQUEDA MASCOTAS PERDIDAS

## Introducci贸n
En el presento documente tendr谩 en detalle cada una de las histor铆as de usuario que ayudar谩n a la construcci贸n del BOT de busqueda de mascotas perdidas.

Las funcionalidades minimas que se deben implementar para dicho Bot son:

Para los usuarios:

 1. Los usuarios pueden registrar una o mas mascotas mediante el bot.
 2. Reportar una mascota registrada como perdida.
 3. Modificacion y baja de la informacion de la mascota.
 4. Regsitrarse en grupos de mensajeria de las zonas.
 5. Reportar avistamiento de las mascotas con una foto.
 6. Solicitar todos los reportes de mascotas perdidas

Para el bot:

 1. Solicitar actualizacion de datos de una mascota registrada en un lapso largo de tiempo (6 meses).
 2. Enviar mensajes a un conjunto de grupos de telegram para informar acerca de un reporte de mascota extraviada.

Para los sponsors (a valida):
 1. Enviar publicidad a una zona despues de un pago. 


## Hist贸rias de Usuario.

### 100 - Modificar o Eliminar registro de mascota.

*Autor*: Bernardo Duran

*Fecha*: 08/03/2022

*Prioridad*: ALTA

#### Descripci贸n
Un `usuario` debe realizar la modificaci贸n o eliminar algun registro de informaci贸n de su `mascota(s)` por medio de la aplicaci贸n, para esto , el usuario debe ingresar el id otorgado al registrar la mascota como perdida, para as铆 continuar con los pasos. 

#### Escenarios
1. Validaci贸n de datos.
2. Ingreso de datos erroneos o falsos.
3. Usuario con un registro de mascota.

#### Casos de Prueba

*100.1.1 Validaci贸n de datos*

Descripci贸n: Un usuario al momento de ingresar los datos que se piden de forma incorecta, se dara a conocer que no esta registrada dicha mascota.

Pasos:

 1. Ingresar al BOT via Telegram y enviar el comando `/start`
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje. "En que puedo ayudarlo:

    1) Registro de mascota
    2) Reportar mascota perdida
    3) Modificar o Eliminar registro de mascota
    4) Registro de grupos de zonas
    5) Avsitamiento de mascota perdida
    6) Todas las mascotas perdidas
    "
 2. El `usuario` env铆a el comando `/ModificarInfo`
    - Datos: comando `/ModificarInfo`
    - Resultado esperado: El BOT retorna un mensaje. "Ingrese el id y nombre de la mascota"   
 3. El `usuario` coloca un espacio en blanco en un campo obligatorio
    - id: Coloca `un espacion en blanco`
    - nombre de la mascota: Coloca `un espacion en blanco`
    - Resultado: El BOT pide nuevamente los datos de campo obligatorio porque no puede ser espacios en blanco.
 4. El `usuario` coloca car谩cteres no convencionales como emojis.
    - id: Coloca ``
    - nombre de la mascota: Coloca ``
    - Resultado: El BOT le indica que no puede colocar caracteres especiales.

*100.1.2 Ingreso de datos erroneos o falsos* 

Descripci贸n: Un usuario al momento que haga una solicitud de modificaci贸n y no ingrese datos que se piden erroneos o falsos se le informar谩 que no existe la mascota con dichos datos dados.

Pasos:

1. El `usuario` coloca un id y/o el nombre incorrecto.
    - id: Coloca `123 (Y era el id: 321)`
    - nombre de la mascota: Coloca `Draco (Y era el nombre: Bruno)`
    - Resultado: El BOT le indica que no se registro ninguna con dicho id y/o nombre.

*100.1.3 Usuario con un registro de mascota*

Descripci贸n: Un usuario al momento que haga una solicitud de modificaci贸n y ingrese datos que se piden correctamente se le mostrar谩 un men煤 donde debe seleccionar si desea modificar la informaci贸n de la mascota y as铆 eliminar la informaci贸n.

Pasos:

1. El `usuario` coloca un id y/o el nombre incorrecto.
    - id: Coloca `321`
    - nombre de la mascota: Coloca `Bruno`
    - Resultado esperado: El BOT retorna un mensaje. "Datos correctos y manda un mensaje de pregunta:"
2. El bot muestra un mensaje.
    - El BOT retorna un mensaje. "Usted encontr贸 a su mascota(Se eliminar谩 los datos de la misma si env铆a un Si)? (Si/No):
3. El `usuario` env铆a el mensaje con la palabra `Si`
    - Datos: mensaje `Si`
    - Resultado esperado: El BOT retorna un mensaje. "Que bueno!!! Se hizo la eliminaci贸n de la informaci贸n de su mascota encontrada"

### 101 - Eliminaci贸n de informaci贸n.

*Autor*: Bernardo Duran

*Fecha*: 08/03/2022

*Prioridad*: MUY ALTA

#### Descripci贸n

Un `Usuario` al momento de confirmar la eliminac贸n de la informaci贸n de su mascota el bot enviara mensajes a los grupos zonales cercanos.

El diagrama de secuencias para la presente hist贸ria es el siguiente:

[plantuml, format="png", id="estados-mascota"]
....
@startuml

[*] --> MODIFICACIN
PERDIDA --> ENCONTRADA

@enduml
....

#### Escenarios
1. Solicitud mascota encontrada APROBADA.
2. Solicitud mascota encontrada RECHAZADA.
3. No se tiene mascotas registradas.

#### Casos de Prueba

*101.1.1 Solicitud mascota encontrada APROBADA* 
Descripci贸n: El `usuario` ingresa datos correctos de su mascota confirma que se encontr贸 la mascota.

Pasos:

 1. Ingresar al BOT via Telegram y enviar el comando `/start`
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje. "En que puedo ayudarlo:

    1) Registro de mascota
    2) Reportar mascota perdida
    3) Modificar o Eliminar registro de mascota
    4) Registro de grupos de zonas
    5) Avsitamiento de mascota perdida
    6) Todas las mascotas perdidas
    "
 2. El `usuario` env铆a el comando `/ModificarInfo`
    - Datos: comando `/ModificarInfo`
    - Resultado esperado: El BOT retorna un mensaje. "Ingrese el id y nombre de la mascota"
 3. El `usuario` coloca un id y/o el nombre incorrecto.
    - id: Coloca `321`
    - nombre de la mascota: Coloca `Bruno`
    - Resultado esperado: El BOT retorna un mensaje. "Datos correctos y manda un mensaje de pregunta:"
 4. El bot muestra un mensaje.
    - El BOT retorna un mensaje. "Usted encontr贸 a su mascota(Se eliminar谩 los datos de la misma si env铆a un Si)? (Si/No):
 5. El `usuario` env铆a el mensaje con la palabra `Si`
    - Datos: mensaje `Si`
    - Resultado esperado: El BOT retorna un mensaje. "Que bueno!!! Se hizo la eliminaci贸n de la informaci贸n de su mascota encontrada"

*101.1.2 Solicitud mascota perdida RECHAZADA* 
Descripci贸n: El `usuario` solicita que uno de sus regsitros de mascotas, sea publicado como mascota perdida, este solo sera rechazado si la mascota ya esta regsitrada como perdida.

Pasos:

 1. Ingresar al BOT via Telegram y enviar el comando `/start`
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje. "En que puedo ayudarlo:

    1) Registro de mascota
    2) Reportar mascota perdida
    3) Modificar o Eliminar registro de mascota
    4) Registro de grupos de zonas
    5) Avsitamiento de mascota perdida
    6) Todas las mascotas perdidas
    "
 2. El `usuario` env铆a el comando `/ModificarInfo`
    - Datos: comando `/ModificarInfo`
    - Resultado esperado: El BOT retorna un mensaje. "Ingrese el id y nombre de la mascota"
 3. El `usuario` coloca un id y/o el nombre incorrecto.
    - id: Coloca `321`
    - nombre de la mascota: Coloca `Bruno`
    - Resultado esperado: El BOT retorna un mensaje. "Datos correctos y manda un mensaje de pregunta:"
 4. El bot muestra un mensaje.
    - El BOT retorna un mensaje. "Usted encontr贸 a su mascota(Se eliminar谩 los datos de la misma si env铆a un Si)? (Si/No):
 5. El `usuario` env铆a el mensaje con la palabra `No`
    - Datos: mensaje `No`
    - Resultado esperado: El BOT retorna un mensaje y posterior env铆a nuevamente el men煤. "Esperemos que aparezca pronto."
 6. El BOT muestra el men煤
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje. "En que puedo ayudarlo:

    1) Registro de mascota
    2) Reportar mascota perdida
    3) Modificar o Eliminar registro de mascota
    4) Registro de grupos de zonas
    5) Avsitamiento de mascota perdida
    6) Todas las mascotas perdidas
    "

*101.2.1 No se tiene mascotas registradas.* 
Descripci贸n: El `usuario` solicita que uno de sus regsitros de mascotas, sea publicado como mascota perdida, si este no tiene niguna mascota registrada sera retornado al inicio.

Pasos:

1. Ingresar al BOT via Telegram y enviar el comando `/start`
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje. "En que puedo ayudarlo:

    1) Regsitro de mascota
    2) Reportar mascota perdida
    3) Modificar o Eliminar registro de mascota
    4) Regsitro de grupos de zonas
    5) Avsitamiento de mascota perdida
    6) Todas las mascotas perdidas
    "

2. El `usuario` env铆a el comando `/ModificarInfo`
    - Datos: comando `/ModificarInfo`
    - Resultado esperado: El BOT retorna un mensaje. "Ingrese el id y nombre de la mascota"
3. El `usuario` coloca un id y/o el nombre incorrecto.
    - id: Coloca `123 (Y era el id: 321)`
    - nombre de la mascota: Coloca `Draco (Y era el nombre: Bruno)`
    - Resultado: El BOT le indica que no se registro ninguna con dicho id y/o nombre y posterior env铆a nuevamente el men煤.
4. El BOT muestra el men煤
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje. "En que puedo ayudarlo:

    1) Registro de mascota
    2) Reportar mascota perdida
    3) Modificar o Eliminar registro de mascota
    4) Registro de grupos de zonas
    5) Avsitamiento de mascota perdida
    6) Todas las mascotas perdidas
    "