= {product} - Histórias de Usuario
Universidad Católica Boliviana. <jose.pozo@ucb.edu.bo>
1.0.0
:product: BOT BUSQUEDA MASCOTAS PERDIDAS

## Introducción
El presento documente tendrá el detalle de todas las historías de usuario para la construcción de un BOT de busqueda de mascotas perdidas.

Se ha establecido que la funcionalidad mínima para la implementación será:

Para los usuarios:

 1. Los usuarios pueden registrar una o mas mascotas mediante el bot.
 2. Reportar una mascota registrada como perdida.
 3. Modificacion y baja de la informacion de la mascota.
 4. Regsitrarse en grupos de mensajeria de las zonas.
 5. Reportar avistamiento de las mascotas con una foto.
 6. Solicitar todos los reportes de mascotas perdidas

Para el bot:

 1. Solicitar actualizacion de datos de una mascota registrada en un lapso largo de tiempo (6 meses).
 2. Enviar mensajes a un conjunto de grupos de telegram para informar acerca de un reporte de mascota extraviada.

Para los sponsors (a valida):
 1. Enviar publicidad a una zona despues de un pago. 


## Histórias de Usuario.

### 200 Reportar mascota extraviada, previamente registrada