= {product} - Hist贸rias de Usuario
Universidad Cat贸lica Boliviana. <rene.vicente@ucb.edu.bo  bernardo.duran@ucb.edu.bo  jose.pozo@ucb.edu.bo>
1.0.0
:product: BOT BUSQUEDA MASCOTAS PERDIDAS

## Introducci贸n
El presento documente tendr谩 el detalle de todas las histor铆as de usuario para la construcci贸n de un BOT de busqueda de mascotas perdidas.

Se ha establecido que la funcionalidad m铆nima para la implementaci贸n ser谩:

Para los usuarios:

 1. Los usuarios pueden registrar una o mas mascotas mediante el bot.
 2. Reportar una mascota registrada como perdida.
 3. Modificacion y baja de la informacion de la mascota.
 4. Regsitrarse en grupos de mensajeria de las zonas.
 5. Reportar avistamiento de las mascotas con una foto.
 6. Solicitar todos los reportes de mascotas perdidas

Para el bot:

 1. Solicitar actualizacion de datos de una mascota registrada en un lapso largo de tiempo (6 meses).
 2. Enviar mensajes a un conjunto de grupos de telegram para informar acerca de un reporte de mascota extraviada.

Para los sponsors (a validar):
 1. Enviar publicidad a una zona despues de un pago. 


## Hist贸rias de Usuario.

### 100 - Regsitro de mascota.

*Autor*: Rene Vicente

*Fecha*: 07/03/2022

*Prioridad*: ALTA

#### Descripci贸n
Un `usuario` debe registrar a su `mascota(s)` por medio de la aplicaci贸n, para esto debe enviar el nombre de la mascota, su descripcion, datos de contacto y una foto de la mascota. Una vez enviado su registro este se almacenara junto a su id en telegram. 
La descrpcion incluira los siguientes datos:
 
 * Especie de la mascota.
 * Raza de la mascota.
 * Genero.
 * Edad.
 * Rasgos caracteristicos (no es un campo obligatorio), como ser marcas, tatuaje de identificacion, etc.
 * Cuidados especiales (no es un campo obligatorio), en caso de una enfermedad o lesion de la mascota a considerar.

#### Escenarios
1. Usuario sin ningun registro de mascota.
2. Validacion de parametros.
3. Usuario con uno o mas registros de mascotas.
4. Usuario con mascota ya registrada.

#### Casos de Prueba

*100.1.1 Usuario sin ningun registro de mascota* 

Descripci贸n: Un usuario que no tenga ningun regsitro de mascotas, y haga una solicitud de registro, pasara automaticamente al formulario de registro de mascota y podra proceder a llenarlo.

Pasos:

 1. Ingresar al BOT via Telegram y enviar el comando `/start`
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje. "En que puedo ayudarlo:

    1) Regsitro de mascota
    2) Reportar mascota perdida
    3) Modificar o Eliminar registro de mascota
    4) Regsitro de grupos de zonas
    5) Avsitamiento de mascota perdida
    6) Todas las mascotas perdidas
    "

 2. El `usuario` env铆a el comando `/registroMascota`
    - Datos: comando `/registroMascota`
    - Resultado esperado: El BOT retorna un mensaje. "Ingrese nombre de la mascota"

 3. El `usuario` ingresa el nombre de la mascota
    - Datos: ingresa el `nombre de la mascota`
    - Resultado esperado: El BOT retorna un mensaje. "Ingrese la especie y raza de la mascota"

 4. El `usuario` ingresa la especie y raza de la mascota
    - Datos: ingresa la `especie y raza de la mascota`
    - Resultado esperado: El BOT retorna un mensaje. "Ingrese la edad de la mascota"

 5. El `usuario` ingresa la edad de la mascota
    - Datos: ingresa la `edad de la mascota`
    - Resultado esperado: El BOT retorna un mensaje. "Ingrese el genero de la mascota"

 6. El `usuario` ingresa el genero de la mascota
    - Datos: ingresa el `genero de la mascota`
    - Resultado esperado: El BOT retorna un mensaje. "Algun rasgo caracteristico de la mascota, este espacio puede estar vacio"

 7. El `usuario` ingresa rasgo caracteristico o deja espacio en blanco
    - Datos: ingresa el `rasgo caracteristico` o deja el `espacio en blanco`
    - Resultado esperado: El BOT retorna un mensaje. "Algun cuidado especial de la mascota, este espacio puede estar vacio"

 8. El `usuario` ingresa cuidado especial o deja espacio en blanco
    - Datos: ingresa el `cuidado especial` o deja el `espacio en blanco`
    - Resultado esperado: El BOT retorna un mensaje. "Algun dato de contacto adicional, este espacio puede estar vacio"

 9. El `usuario` ingresa contactos adicionales o deja espacio en blanco
    - Datos: ingresa el `contactos adicionales` o deja el `espacio en blanco`
    - Resultado esperado: El BOT retorna un mensaje. "Suba una foto de su mascota"

 10. El `usuario` envia una foto de su mascota
    - Datos: envio de un `archivo de imagen`
    - Resultado esperado: El BOT retorna un mensaje. "Regsitro completado"

*100.1.2 Validacion de parametros* 

Descripci贸n: Un usuario al momento de llenar el registro de mascota ingresa parametros no permitidos, en cualquier parte del formulario estos seran rechazados.

Pasos:

 1. El `usuario` coloca un espacio en blanco en un campo obligatorio
    - Datos: Coloca `un espacion en blanco`
    - Resultado: El BOT pide nuevamente el dato de campo obligatorio porque no puede ser espacios en blanco.
 2. El `usuario` coloca car谩cteres no convencionales como emojis.
    - Datos: Coloca ``
    - Resultado: El BOT le indica que no puede colocar caracteres especiales.

*100.2.1 Usuario con uno o mas registros de mascotas* 

Descripci贸n: Un usuario que tenga algun regsitro de mascota, y haga una solicitud de registro, se le mostrara un resumen de los regsitros que tenga y luego pasara al formulario de registro de mascota y podra proceder a llenarlo.

Pasos:

 1. Ingresar al BOT via Telegram y enviar el comando `/start`
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje. "En que puedo ayudarlo:

    1) Regsitro de mascota
    2) Reportar mascota perdida
    3) Modificar o Eliminar registro de mascota
    4) Regsitro de grupos de zonas
    5) Avsitamiento de mascota perdida
    6) Todas las mascotas perdidas
    "

 2. El `usuario` env铆a el comando `/registroMascota`
    - Datos: comando `/registroMascota`
    - Resultado esperado: El BOT retorna un mensaje. "Tiene registrados a las siguientes mascotas:

    1) Especie y raza: Perro, mestizo
    Nombre: Se帽or Gato
    2) Especie y raza: Gato, atigrado
    Nombre: Joven Perro

    Desea continuar con el registro si/no:
    "

 3. El `usuario` ingresa el comando `/si`
    - Datos: ingresa el comando `/si`
    - Resultado esperado: El BOT retorna un mensaje. "Ingrese el nombre de la mascota"

 4. El `usuario` ingresa el nombre de la mascota
    - Datos: ingresa el `nombre de la mascota`
    - Resultado esperado: El BOT retorna un mensaje. "Ingrese la especie y raza de la mascota"

 5. El `usuario` ingresa la especie y raza de la mascota
    - Datos: ingresa la `especie y raza de la mascota`
    - Resultado esperado: El BOT retorna un mensaje. "Ingrese la edad de la mascota"

 6. El `usuario` ingresa la edad de la mascota
    - Datos: ingresa la `edad de la mascota`
    - Resultado esperado: El BOT retorna un mensaje. "Ingrese el genero de la mascota"

 7. El `usuario` ingresa el genero de la mascota
    - Datos: ingresa el `genero de la mascota`
    - Resultado esperado: El BOT retorna un mensaje. "Algun rasgo caracteristico de la mascota, este espacio puede estar vacio"

 8. El `usuario` ingresa rasgo caracteristico o blanco
    - Datos: ingresa el `rasgo caracteristico` o deja el `espacio en blanco`
    - Resultado esperado: El BOT retorna un mensaje. "Algun cuidado especial de la mascota, este espacio puede estar vacio"

 9. El `usuario` ingresa cuidado especial o blanco
    - Datos: ingresa el `cuidado especial` o deja el `espacio en blanco`
    - Resultado esperado: El BOT retorna un mensaje. "Algun dato de contacto adicional, este espacio puede estar vacio"

 10. El `usuario` ingresa contactos adicionales o blanco
    - Datos: ingresa el `contactos adicionales` o deja el `espacio en blanco`
    - Resultado esperado: El BOT retorna un mensaje. "Suba una foto de su mascota"

 11. El `usuario` envia una foto de su mascota
    - Datos: envio de un `archivo de imagen`
    - Resultado esperado: El BOT retorna un mensaje. "Regsitro completado"

*100.2.2 Usuario con mascota ya registrada.* 

Descripci贸n: Un usuario que tenga algun regsitro de mascota, y haga una solicitud de registro, se le mostrara un resumen de los regsitros que tenga, al ya tener el regsitro cancela el `registro de mascota` y retornara a al index o inicio.

Pasos:

 1. Ingresar al BOT via Telegram y enviar el comando `/start`
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje. "En que puedo ayudarlo:

    1) Regsitro de mascota
    2) Reportar mascota perdida
    3) Modificar o Eliminar registro de mascota
    4) Regsitro de grupos de zonas
    5) Avsitamiento de mascota perdida
    6) Todas las mascotas perdidas
    "

 2. El `usuario` env铆a el comando `/registroMascota`
    - Datos: comando `/registroMascota`
    - Resultado esperado: El BOT retorna un mensaje. "Tiene registrados a las siguientes mascotas:

    1) Especie y raza: Perro, mestizo
    Nombre: Se帽or Gato
    2) Especie y raza: Gato, atigrado
    Nombre: Joven Perro

    Desea continuar con el registro si/no:
    "

 3. El `usuario` ingresa el comando `/no`
    - Datos: ingresa el comando `/no`
    - Resultado esperado: El BOT retorna al inicio o index

### 101 - Reportar una mascota registrada como perdida.

*Autor*: Rene Vicente

*Fecha*: 07/03/2022

*Prioridad*: MUY ALTA

#### Descripci贸n

Un `Usuario` debe poder solicitar que un registro de mascota en el sistema sea declarado como perdido, al momento de declarar la perdida el bot enviara mensajes a los grupos zonales cercanos.

El diagrama de secuencias para la presente hist贸ria es el siguiente:

[plantuml, format="png", id="estados-mascota"]
....
@startuml

[*] --> REGISTRADO
REGISTRADO --> PERDIDA
PERDIDA --> ENCONTRADA
ENCONTRADA --> REGISTRADO

@enduml
....

#### Escenarios
1. Solicitud mascota perdida APROBADA.
2. Solicitud mascota perdida RECHAZADA.
3. No se tiene mascotas registradas.

#### Casos de Prueba

*101.1.1 Solicitud mascota perdida APROBADA* 
Descripci贸n: El `usuario` solicita que uno de sus regsitros de mascotas, sea publicado como mascota perdida.

Pasos:

1. Ingresar al BOT via Telegram y enviar el comando `/start`
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje. "En que puedo ayudarlo:

    1) Regsitro de mascota
    2) Reportar mascota perdida
    3) Modificar o Eliminar registro de mascota
    4) Regsitro de grupos de zonas
    5) Avsitamiento de mascota perdida
    6) Todas las mascotas perdidas
    "

 2. El `usuario` env铆a el comando `/reportarPerdido`
    - Datos: comando `/reportarPerdido`
    - Resultado esperado: El BOT retorna un mensaje. "Tiene registrados a las siguientes mascotas:

    1) Especie y raza: Perro, mestizo
    Nombre: Se帽or Gato
    2) Especie y raza: Gato, atigrado
    Nombre: Joven Perro

    ingrese el numero de la mascota, si deja el espacio en blanco o ingresa un valor no listado se retornara a inicio:
    "

 3. El `usuario` ingresa el comando `1`
    - Datos: ingresa el comando `1`
    - Resultado esperado: El BOT retorna un mensaje. "Seleccione la zona donde fue el ultimo contacto con la mascota
    
    * Sopocachi
    * Miraflores
    * Zona Sur
    * ...
    "

 4. El `usuario` selecciona `Sopocachi`
    - Datos: seleccion `Sopocachi`
    - Resultado esperado: El BOT retorna un mensaje. "Su reporte sera enviado a los siguientes grupos 
    
    * Sopocachi
    * Miraflores
    * San Pedro 
    * ...
    "

 5. El `BOT` Envia el registro de la mascota a los grupos cercanos
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje en varios grupos. "Se perdio la mascota:
    
    * Nombre:
    * Especie y raza:
    * Edad:
    * Genero:
    * Rasgos caracteristicos:
    * En: Sopocachi 
    * Imagen: 
    "

*101.1.2 Solicitud mascota perdida RECHAZADA* 
Descripci贸n: El `usuario` solicita que uno de sus regsitros de mascotas, sea publicado como mascota perdida, este solo sera rechazado si la mascota ya esta regsitrada como perdida.

Pasos:

1. Ingresar al BOT via Telegram y enviar el comando `/start`
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje. "En que puedo ayudarlo:

    1) Regsitro de mascota
    2) Reportar mascota perdida
    3) Modificar o Eliminar registro de mascota
    4) Regsitro de grupos de zonas
    5) Avsitamiento de mascota perdida
    6) Todas las mascotas perdidas
    "

 2. El `usuario` env铆a el comando `/reportarPerdido`
    - Datos: comando `/reportarPerdido`
    - Resultado esperado: El BOT retorna un mensaje. "Tiene registrados a las siguientes mascotas:

    1) Especie y raza: Perro, mestizo
    Nombre: Se帽or Gato
    2) Especie y raza: Gato, atigrado
    Nombre: Joven Perro

    ingrese el numero de la mascota, si deja el espacio en blanco o ingresa un valor no listado se retornara a inicio:
    "

 3. El `usuario` ingresa el comando `1`
    - Datos: ingresa el comando `1`
    - Resultado esperado: El BOT retorna un mensaje. "Solicitud RECHAZADA
    su mascota ya esta registrada como perdida", El bot regresa al inicio

*101.2.1 No se tiene mascotas registradas.* 
Descripci贸n: El `usuario` solicita que uno de sus regsitros de mascotas, sea publicado como mascota perdida, si este no tiene niguna mascota registrada sera retornado al inicio.

Pasos:

1. Ingresar al BOT via Telegram y enviar el comando `/start`
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje. "En que puedo ayudarlo:

    1) Regsitro de mascota
    2) Reportar mascota perdida
    3) Modificar o Eliminar registro de mascota
    4) Regsitro de grupos de zonas
    5) Avsitamiento de mascota perdida
    6) Todas las mascotas perdidas
    "

 2. El `usuario` env铆a el comando `/reportarPerdido`
    - Datos: comando `/reportarPerdido`
    - Resultado esperado: El BOT retorna un mensaje. "No tiene ningun registro de mascotas, Para regsitrar mascotas ingrese el comando `/regsitrarMascota` en el inicio", El bot retorna al inicio

### 102 - Modificar y baja de la informacion de la mascota.

*Autor*: Bernardo Duran

*Fecha*: 08/03/2022

*Prioridad*: ALTA

#### Descripci贸n
Un `usuario` debe poder realizar la modificaci贸n del registro de la mascota, como tambien dar de baja esta informacion, para que el `Bot` pueda hacer la eliminaci贸n o modificacion del registro de informaci贸n de su `mascota(s)`, el usuario debe tener un registro de mascota, ingresar el id otorgado al listar su mascota, para as铆 continuar con los pasos. 

El diagrama de secuencias para la presente hist贸ria es el siguiente:

[plantuml, format="png", id="secuencia_mod"]
....
@startuml

title "Messages - Sequence Diagram"

actor Usuario
boundary "BOT GUI" as GUI
control "BOT Control" as SC
entity BOT
database BOTDB

Usuario -> GUI : "/start"
GUI -> Usuario : "opciones"
Usuario -> GUI : "/ModificaInfo"
GUI -> SC : "Solicitud de mascotas"
SC -> BOT : "validado obtener mascotas" 
BOT -> BOTDB : "obtener mascotas"
BOTDB -> BOT: "lista mascotas"
BOT -> SC: "Lista mascotas"
SC -> GUI: "Lista mascotas"
Usuario -> GUI: "/1"
GUI -> SC: "OPCION 1"
SC -> BOT: "validado a modificar 1"
BOT -> SC: "Sol. nuevos datos"
SC -> GUI: "Datos validados a modificar"
Usuario -> GUI: "DATOS"
GUI ->SC : "DATOS"
SC -> BOT: "DATOS VALIDADOS"
BOT -> BOTDB: "ALMACENAR DATOS"
@enduml
....

#### Escenarios
1. Validaci贸n de datos.
2. Ingreso de datos erroneos o falsos.
3. Usuario con un registro de mascota.
4. Solicitud de mascota ha eliminar APROBADA.
5. Solicitud de mascota ha eliminar RECHAZADA.
6. No se tiene mascotas registradas.

#### Casos de Prueba

*102.1.1 Validaci贸n de datos*

Descripci贸n: Un usuario al momento de ingresar los datos que se piden de forma incorecta, se dara a conocer que no esta registrada dicha mascota.

Pasos:

 1. Ingresar al BOT via Telegram y enviar el comando `/start`
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje. "En que puedo ayudarlo:

    1) Registro de mascota
    2) Reportar mascota perdida
    3) Modificar o Eliminar registro de mascota
    4) Registro de grupos de zonas
    5) Avsitamiento de mascota perdida
    6) Todas las mascotas perdidas
    "
 2. El `usuario` env铆a el comando `/ModificarInfo`
    - Datos: comando `/ModificarInfo`
    - Resultado esperado: El BOT retorna un mensaje. "Ingrese el id y nombre de la mascota"   
 3. El `usuario` coloca un espacio en blanco en un campo obligatorio
    - id: Coloca `un espacion en blanco`
    - nombre de la mascota: Coloca `un espacion en blanco`
    - Resultado: El BOT pide nuevamente los datos de campo obligatorio porque no puede ser espacios en blanco.
 4. El `usuario` coloca car谩cteres no convencionales como emojis.
    - id: Coloca ``
    - nombre de la mascota: Coloca ``
    - Resultado: El BOT le indica que no puede colocar caracteres especiales.

*102.1.2 Ingreso de datos erroneos o falsos* 

Descripci贸n: Un usuario al momento que haga una solicitud de modificaci贸n y no ingrese datos que se piden erroneos o falsos se le informar谩 que no existe la mascota con dichos datos dados.

Pasos:

1. El `usuario` coloca un id y/o el nombre incorrecto.
    - id: Coloca `123 (Y era el id: 321)`
    - nombre de la mascota: Coloca `Draco (Y era el nombre: Bruno)`
    - Resultado: El BOT le indica que no se registro ninguna con dicho id y/o nombre.

*102.2.1 Usuario con un registro de mascota*

Descripci贸n: Un usuario al momento que haga una solicitud de modificaci贸n y ingrese datos que se piden correctamente se le mostrar谩 un men煤 donde debe seleccionar si desea modificar la informaci贸n de la mascota y as铆 eliminar la informaci贸n.

Pasos:

1. El `usuario` coloca un id y/o el nombre correcto.
    - id: Coloca `321`
    - nombre de la mascota: Coloca `Bruno`
    - Resultado esperado: El BOT retorna un mensaje. "Datos correctos y manda un mensaje de pregunta:"
2. El bot muestra un mensaje.
    - El BOT retorna un mensaje. "Desea elminar o modificar a esta mascota: `Bruno` (Si/No):
3. El `usuario` env铆a el mensaje con la palabra `Si`
    - Datos: mensaje `Si`
    - Resultado esperado: El BOT retorna un mensaje. "Complete el formulario por favor" El bot realiza la historia de usuario #100

*102.3.1 Solicitud mascota encontrada APROBADA* 
Descripci贸n: El `usuario` ingresa datos correctos de su mascota confirma que se encontr贸 la mascota.

Pasos:

 1. Ingresar al BOT via Telegram y enviar el comando `/start`
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje. "En que puedo ayudarlo:

    1) Registro de mascota
    2) Reportar mascota perdida
    3) Modificar o Eliminar registro de mascota
    4) Registro de grupos de zonas
    5) Avsitamiento de mascota perdida
    6) Todas las mascotas perdidas
    "
 2. El `usuario` env铆a el comando `/ModificarInfo`
    - Datos: comando `/ModificarInfo`
    - Resultado esperado: El BOT retorna un mensaje. "Ingrese el id y nombre de la mascota"
 3. El `usuario` coloca un id y/o el nombre incorrecto.
    - id: Coloca `321`
    - nombre de la mascota: Coloca `Bruno`
    - Resultado esperado: El BOT retorna un mensaje. "Datos correctos y manda un mensaje de pregunta:"
 4. El bot muestra un mensaje.
    - El BOT retorna un mensaje. "Usted encontr贸 a su mascota(Se eliminar谩 los datos de la misma si env铆a un Si)? (Si/No):
 5. El `usuario` env铆a el mensaje con la palabra `Si`
    - Datos: mensaje `Si`
    - Resultado esperado: El BOT retorna un mensaje. "Que bueno!!! Se hizo la eliminaci贸n de la informaci贸n de su mascota encontrada"

*102.3.2 Solicitud mascota perdida RECHAZADA* 
Descripci贸n: El `usuario` solicita que uno de sus regsitros de mascotas, sea publicado como mascota perdida, este solo sera rechazado si la mascota ya esta regsitrada como perdida.

Pasos:

 1. Ingresar al BOT via Telegram y enviar el comando `/start`
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje. "En que puedo ayudarlo:

    1) Registro de mascota
    2) Reportar mascota perdida
    3) Modificar o Eliminar registro de mascota
    4) Registro de grupos de zonas
    5) Avsitamiento de mascota perdida
    6) Todas las mascotas perdidas
    "
 2. El `usuario` env铆a el comando `/ModificarInfo`
    - Datos: comando `/ModificarInfo`
    - Resultado esperado: El BOT retorna un mensaje. "Ingrese el id y nombre de la mascota"
 3. El `usuario` coloca un id y/o el nombre incorrecto.
    - id: Coloca `321`
    - nombre de la mascota: Coloca `Bruno`
    - Resultado esperado: El BOT retorna un mensaje. "Datos correctos y manda un mensaje de pregunta:"
 4. El bot muestra un mensaje.
    - El BOT retorna un mensaje. "Usted encontr贸 a su mascota? (Si/No):
 5. El `usuario` env铆a el mensaje con la palabra `No`
    - Datos: mensaje `No`
    - Resultado esperado: El BOT retorna un mensaje y posterior env铆a nuevamente el men煤. "Esperemos que aparezca pronto."
 6. El BOT muestra el men煤
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje. "En que puedo ayudarlo:

    1) Registro de mascota
    2) Reportar mascota perdida
    3) Modificar o Eliminar registro de mascota
    4) Registro de grupos de zonas
    5) Avsitamiento de mascota perdida
    6) Todas las mascotas perdidas
    "

*102.4.1 No se tiene mascotas registradas.* 
Descripci贸n: El `usuario` solicita que uno de sus regsitros de mascotas, sea publicado como mascota perdida, si este no tiene niguna mascota registrada sera retornado al inicio.

Pasos:

1. Ingresar al BOT via Telegram y enviar el comando `/start`
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje. "En que puedo ayudarlo:

    1) Regsitro de mascota
    2) Reportar mascota perdida
    3) Modificar o Eliminar registro de mascota
    4) Regsitro de grupos de zonas
    5) Avsitamiento de mascota perdida
    6) Todas las mascotas perdidas
    "

2. El `usuario` env铆a el comando `/ModificarInfo`
    - Datos: comando `/ModificarInfo`
    - Resultado esperado: El BOT retorna un mensaje. "Ingrese el id y nombre de la mascota"
3. El `usuario` coloca un id y/o el nombre incorrecto.
    - id: Coloca `123 (Y era el id: 321)`
    - nombre de la mascota: Coloca `Draco (Y era el nombre: Bruno)`
    - Resultado: El BOT le indica que no se registro ninguna con dicho id y/o nombre y posterior env铆a nuevamente el men煤.
4. El BOT muestra el men煤
    - Datos: NINGUNO
    - Resultado esperado: El BOT retorna un mensaje. "En que puedo ayudarlo:

    1) Registro de mascota
    2) Reportar mascota perdida
    3) Modificar o Eliminar registro de mascota
    4) Registro de grupos de zonas
    5) Avsitamiento de mascota perdida
    6) Todas las mascotas perdidas
    "

### 103 - Regsitrarse en grupos de mensajeria de las zonas

*Autor*: Jose Pozo Silva

*Fecha*: 03/10/2022

*Prioridad*: ALTA

#### Descripci贸n


Un `usuario` primeramente debera registrarse en la aplicacion `Telegram`, una vez ya creada la cuenta, debera buscar el grupo de la zona a la cual desea ingresar, una vez localize el grupo de la zona, debe precionar la opcion unirse, y en ese momento se le pedira que se registre con los siguientes datos:

   *  Nombre Completo
   *  Numero de Documento de Identidad
   *  Edad
   *  Numero de Celular
   *  Correo Electronico
   *  Direccion de Domicilio
 
 

#### Escenarios
1. Usuario no registrado en un grupo de zonas.

2. validadcion de Informacion.

3. Usuario Registrado en mas de un grupo (zona)

4. Registro no completado y/o finalizado


#### Casos de Prueba

*103.1.1 Usuario no registrado en grupo de zonas*

Descripcion: Un Usuario que no este registrado en un grupo y desee ingresar a un grupo de una zona en especifico, primeramente debera
registrar sus datos personales

pasos:

1. Ingresar al bot de telegram y enviar el comando '/start'

   - Datos: NINGUNO
   - Resultado esperado: El bot enviara el siguiente mensaje. "Hola, Binevenido. Porfavor Seleccione una opcion

      1) Regsitro de mascota
      2) Reportar mascota perdida
      3) Modificar o Eliminar registro de mascota
      4) Regsitro de grupos de zonas
      5) Avsitamiento de mascota perdida
      6) Todas las mascotas perdidas
      
   "

2. El Usuario enviara el comando '/registroGrupo'
   -  Datos: comando "/registroGrupo"
   -  Resultado Esperado: El bot enviara el siguiente mensaje "Porfavor, Ingresa tu Numero de Documento de Identidad"

3. El Usuario Ingresa su numero de documento de identidad
   -  Datos: Ingresa tu numero de documento de identidad
   -  Resultado esperado: El bot retornara el siguiente mensaje "Porfavor, ingresa tu nombre completo"

4. El Usuario ingresa y envia su Nombre completo
   -  Datos: Ingrese tu nombre completo (nombre completo del usuario)
   -  Resultado Esperado: El bot retorna el siguiente mensjae "Ingresa tu edad"

5. El usuario ingresa y envia su edad
   -  Datos: Ingresa tu edad (edad del usuario)
   -  Resultado Esperado: EL bot retorna el siguiente mensaje "Ingresa tu numero de celular"

6. El usuario ingresa y envia su numero de celular
   -  Datos: Ingresa tu numero de celular
   -  Resultado Esperado: El bot retorna el siguiente mensaje "Ingresa tu correo electronico"

7. El usuario ingresa y envia su correo electronico
   -  Datos: Ingresa tu correo electronico
   -  Resultado Esperado: EL bot retornara el siguiente mensaje "Ingresa la direccion de tu Domicilio"

8. El usario ingresa y envia su direccion de domicilio
   -  Datos: Ingresa tu Direccion de Domicilio
   -  Resultado Esperado: El bot retornara el siguiente mensaje "Selcciona una zona a la que quieres ingresar 
         *  1. OBRAJES
         *  2. SAN MIGUEL
         *  3. CALACOTO
         *  4. ACHUMANI
         *  5. IRPAVI
         *  6. LLOJETA
         *  7. MIRAFLORES
         *  8. SOPOCACHI
         *  9. COTAHUMA 
   "
9. El usuario seleccionara y enviara una opcion con el comando '/"numero de lista"'
   -  Datos: Seleccione una opcion de la lista de zonas.
   -  Resultado esperado: El bot retornara el siguiente mensaje "Usted a seleccionado la zoma (---------), para acceder al grupo, haga 
                                                               click en el siguiente enlace"

10. El usuario entrara en el grupo seleccionado
   -  Datos: Usuario registrado en el grupo de una zona seleccionada.
   -  Resultado esperado: El bot retornara el siguiente mensaje "Bienvenido al grupo de mascotas desaparecidas de la zona (-------------)"

*103.2.1 Validacion de parametros*


Descripci贸n: Un usuario al momento de llenar el registro de su usuario, ingresa parametros no permitidos, en cualquier parte del formulario estos seran rechazados.

Casos:

 1. El `usuario` ingresa caracteres simbolos en los campos de texto

    - Datos: El usuario ingresa simbolos y pretende enviarlos (a exepcion del simbolo (arroba"@" para el capo correo electronico))
    - Resultado: El BOT retorna el mensaje "caracteres no permitidos, verifique e intente nuevamente"

 2. El `usuario` coloca car谩cteres no convencionales como emojis.
    - Datos: Coloca ``
    - Resultado: El BOT le indica que no puede colocar caracteres especiales.

3. El usuario ingresa caracteres no permitidos para el dato solicitado
   -  Datos: Ingresa caracteres diferentes a numeros en el campo edad
   -  Resultado Esperado: El bor retornara el mensaje "Tipo de dato no permitido, verifique e intente nuevamente"


*103.3.1 Usuario Registrado en mas de un grupo (zona)*

Descripcion: Un usuario que ya este registrado, e intenra entrar a un grupo de zona adicional, se lo reconocera por el numero de documento de
identidad, y se le enviara a la ultima opcion de registro para seleccionar una zona

pasos:
   
   1. Ingresar al bot de telegram y enviar el comando '/start'

   - Datos: NINGUNO
   - Resultado esperado: El bot enviara el siguiente mensaje. "Hola, Binevenido. Porfavor Seleccione una opcion

      1) Regsitro de mascota
      2) Reportar mascota perdida
      3) Modificar o Eliminar registro de mascota
      4) Regsitro de grupos de zonas
      5) Avsitamiento de mascota perdida
      6) Todas las mascotas perdidas
   "

2. El Usuario enviara el comando '/registroGrupo'
   -  Datos: comando "/registroGrupo"
   -  Resultado Esperado: El bot enviara el siguiente mensaje "Porfavor, Ingresa tu Numero de Documento de Identidad"

3. El Usuario Ingresa su numero de documento de identidad
   -  Datos: Ingresa tu numero de documento de identidad
   -  Resultado Esperado: El bot retornara el siguiente mensaje "Usuario ya registrado en la base de datos, desea unirse a otro grupo
                                                                 de otra zona    1. Si    2. NO "

4. El Usuario Selecciona una opcion, en caso de ser (SI), se le enviara a escoger una zona.
   -  Dato: Respuesta de Usuario (SI)
   -  Resultado Esperado: El bot retornara el siguiente mensaje "Selcciona una zona a la que quieres ingresar 
         *  1. OBRAJES
         *  2. SAN MIGUEL
         *  3. CALACOTO
         *  4. ACHUMANI
         *  5. IRPAVI
         *  6. LLOJETA
         *  7. MIRAFLORES
         *  8. SOPOCACHI
         *  9. COTAHUMA 
   "
5. El usuario seleccionara y enviara una opcion con el comando '/"numero de lista"'
   -  Datos: Seleccione una opcion de la lista de zonas.
   -  Resultado esperado: El bot retornara el siguiente mensaje "Usted a seleccionado la zoma (---------), para acceder al grupo, haga 
                                                               click en el siguiente enlace (----------------link)"

6 El usuario entrara en el grupo seleccionado
   -  Datos: Usuario registrado en el grupo de una zona seleccionada.
   -  Resultado esperado: El bot retornara el siguiente mensaje "Bienvenido al grupo de mascotas desaparecidas de la zona (-------------)"
   
*103.4.1. Registro no completado y/o finalizado*

Descripcion: Si el usuario, al momento de registrar sus datos, no finaliza en un intervalo de tiempo definido, o si decide abandonar el 
registro, el bot, redireccionara al menu principal.

casos:

1. Ingresar al bot de telegram y enviar el comando '/start'

   - Datos: NINGUNO
   - Resultado esperado: El bot enviara el siguiente mensaje. "Hola, Binevenido. Porfavor Seleccione una opcion

      1) Regsitro de mascota
      2) Reportar mascota perdida
      3) Modificar o Eliminar registro de mascota
      4) Regsitro de grupos de zonas
      5) Avsitamiento de mascota perdida
      6) Todas las mascotas perdidas
      
   "

2. El Usuario enviara el comando '/registroGrupo'
   -  Datos: comando "/registroGrupo"
   -  Resultado Esperado: El bot enviara el siguiente mensaje "Porfavor, Ingresa tu Numero de Documento de Identidad"

3. El Usuario Ingresa su numero de documento de identidad
   -  Datos: Ingresa tu numero de documento de identidad
   -  Resultado esperado: El bot retornara el siguiente mensaje "Porfavor, ingresa tu nombre completo"

4. El usuario no responde en 5 minutos.
   -  Datos: Sin respuesta
   -  Resultado Esperado: El bot retornara el siguiente mensaje "Tiempo de respusta superado, Registro cancelado "
